[package]
name = "milvus-sdk-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "milvus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tonic = "0.7"
prost = "0.10"
tokio = { version = "1.17.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.7"
